name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install dependencies
      run: sudo apt-get install -y build-essential

    - name: Configure CMake
      run: cmake .

    - name: Build with CMake
      run: cmake --build .

    - name: List files for debugging
      run: ls -al

    - name: Run the tests
      run: ./tic_tac_game
